import type { Metadata } from "next";

import "./globals.css";
import Navbar from "../components/navbar/Navbar";



export const metadata: Metadata = {
  title: "Slicing Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="">
        <Navbar />
        <main className="">
          {children}
        </main>
      </body>
    </html>
  );
}
